#!/bin/bash

pid () { xdotool search --onlyvisible --name $1; }
rule () { bspc rule -a $1 -o state=floating sticky=on; }
move () { wmctrl -i -r $1 -e $2; }

if [ -z $(pid "irssi") ]; then
	rule "konsole"
	konsole -e irssi &
	sleep 2
	move $(pid "irssi") "0,10,1761,800,385"
fi
if [ -z $(pid "Keep") ]; then
	rule "Firefox"
	firefox -new-window "https://keep.google.com" &
	sleep 5
	move $(pid "Keep") "0,10,1100,800,647"
fi
if [ -z $(pid "Inoreader") ]; then
	rule "Firefox"
	firefox -new-window "https://www.inoreader.com/all_articles" &
	sleep 3
	move $(pid "Inoreader") "0,10,504,800,582"
fi
