#!/bin/bash

sleep 5

# irssi
bspc rule -a konsole -o state=floating sticky=on
konsole -e irssi &
sleep 1
wmctrl -i -r $(xdotool search --onlyvisible --name irssi) -e 0,10,1761,800,385

# google keep
bspc rule -a Firefox -o state=floating sticky=on
firefox -new-window "https://keep.google.com" &
sleep 4
wmctrl -i -r $(xdotool search --onlyvisible --name Keep) -e 0,10,1100,800,647

# inoreader
bspc rule -a Firefox -o state=floating sticky=on
firefox -new-window "https://www.inoreader.com/all_articles" &
sleep 4
wmctrl -i -r $(xdotool search --onlyvisible --name Inoreader) -e 0,10,504,800,582
